#!/bin/sh
set -eu

# 镜像只托管静态前端；上游 Base URL / API Key 在浏览器管理页配置。
echo "[ciallo] static SPA mode — no CIALLO_UPSTREAM (configure API in Web Admin)"

# nginx 模板无上游变量；直接拷贝即可
if [ -f /etc/nginx/nginx.conf.template ]; then
  cp /etc/nginx/nginx.conf.template /etc/nginx/nginx.conf
fi

# 站长账号：.env 注入用户名 + 密码哈希（不把明文密码写进前端）
# 管理页仅该账号（role=admin）可进入；无单独管理密码
MASTER_USER="$(printf '%s' "${CIALLO_MASTER_USERNAME:-}" | tr -d '\r' | tr '[:upper:]' '[:lower:]')"
MASTER_PASSWORD="$(printf '%s' "${CIALLO_MASTER_PASSWORD:-}" | tr -d '\r')"
MASTER_HASH=""

if [ -z "$MASTER_USER" ]; then
  MASTER_USER="admin"
fi

if [ -n "$MASTER_PASSWORD" ]; then
  if command -v sha256sum >/dev/null 2>&1; then
    MASTER_HASH="$(printf '%s' "$MASTER_PASSWORD" | sha256sum | awk '{print $1}')"
  elif command -v openssl >/dev/null 2>&1; then
    MASTER_HASH="$(printf '%s' "$MASTER_PASSWORD" | openssl dgst -sha256 | awk '{print $NF}')"
  else
    echo "[ciallo] warn: no sha256 tool; master password not injected" >&2
    MASTER_HASH=""
  fi
fi

if [ -n "$MASTER_HASH" ]; then
  echo "[ciallo] station master: user=${MASTER_USER} (password from env, hash only in runtime-config)"
else
  echo "[ciallo] station master: not set in env — frontend falls back to mock admin/admin123"
  MASTER_USER=""
  MASTER_HASH=""
fi

# 转义用户名中的引号，避免破坏 JS
MASTER_USER_JS="$(printf '%s' "$MASTER_USER" | sed 's/\\/\\\\/g; s/"/\\"/g')"

# 可选：CF Worker 媒体基址 / 上传 token（非 Telegram Bot Token）
MEDIA_BASE="$(printf '%s' "${CIALLO_MEDIA_BASE:-}" | tr -d '\r')"
MEDIA_UPLOAD_TOKEN="$(printf '%s' "${CIALLO_MEDIA_UPLOAD_TOKEN:-}" | tr -d '\r')"
MEDIA_BASE_JS="$(printf '%s' "$MEDIA_BASE" | sed 's/\\/\\\\/g; s/"/\\"/g')"
MEDIA_TOKEN_JS="$(printf '%s' "$MEDIA_UPLOAD_TOKEN" | sed 's/\\/\\\\/g; s/"/\\"/g')"
if [ -n "$MEDIA_BASE" ]; then
  echo "[ciallo] media worker base: ${MEDIA_BASE}"
fi

# 社区持久化：Docker 默认 http 模式（数据在 /data volume）
COMMUNITY_MODE="$(printf '%s' "${CIALLO_COMMUNITY_MODE:-http}" | tr -d '\r' | tr '[:upper:]' '[:lower:]')"
if [ "$COMMUNITY_MODE" != "mock" ]; then
  COMMUNITY_MODE="http"
fi
COMMUNITY_API_BASE="$(printf '%s' "${CIALLO_COMMUNITY_API_BASE:-/api/community}" | tr -d '\r')"
COMMUNITY_API_BASE_JS="$(printf '%s' "$COMMUNITY_API_BASE" | sed 's/\\/\\\\/g; s/"/\\"/g')"
echo "[ciallo] community mode: ${COMMUNITY_MODE} base=${COMMUNITY_API_BASE} data=${CIALLO_DATA_DIR:-/data}"

# 版本检测：镜像构建时写入的 BUILD_ID / 跟踪分支 / 仓库（可被运行时 env 覆盖）
BUILD_ID="$(printf '%s' "${CIALLO_BUILD_ID:-}" | tr -d '\r')"
if [ -z "$BUILD_ID" ] && [ -f /opt/ciallo/BUILD_ID ]; then
  BUILD_ID="$(tr -d '\r\n' < /opt/ciallo/BUILD_ID | head -c 64)"
fi
TRACK_REF="$(printf '%s' "${CIALLO_TRACK_REF:-beta}" | tr -d '\r')"
if [ -z "$TRACK_REF" ]; then
  TRACK_REF="beta"
fi
GITHUB_REPO="$(printf '%s' "${CIALLO_GITHUB_REPO:-MurasameCyan/CialloStudio}" | tr -d '\r')"
if [ -z "$GITHUB_REPO" ]; then
  GITHUB_REPO="MurasameCyan/CialloStudio"
fi
BUILD_ID_JS="$(printf '%s' "$BUILD_ID" | sed 's/\\/\\\\/g; s/"/\\"/g')"
TRACK_REF_JS="$(printf '%s' "$TRACK_REF" | sed 's/\\/\\\\/g; s/"/\\"/g')"
GITHUB_REPO_JS="$(printf '%s' "$GITHUB_REPO" | sed 's/\\/\\\\/g; s/"/\\"/g')"
if [ -n "$BUILD_ID" ]; then
  echo "[ciallo] build: ${BUILD_ID} track=${TRACK_REF} repo=${GITHUB_REPO}"
else
  echo "[ciallo] build: (unknown) track=${TRACK_REF} repo=${GITHUB_REPO}"
fi

RUNTIME_JS="/usr/share/nginx/html/runtime-config.js"
cat > "$RUNTIME_JS" <<EOF
/* generated by entrypoint — do not edit */
window.__CIALLO_RUNTIME__ = {
  masterUsername: "${MASTER_USER_JS}",
  masterPasswordSha256: "${MASTER_HASH}",
  mediaBase: "${MEDIA_BASE_JS}",
  mediaUploadToken: "${MEDIA_TOKEN_JS}",
  communityMode: "${COMMUNITY_MODE}",
  communityApiBase: "${COMMUNITY_API_BASE_JS}",
  buildId: "${BUILD_ID_JS}",
  githubRepo: "${GITHUB_REPO_JS}",
  trackRef: "${TRACK_REF_JS}"
};
EOF

# 启动社区 API（用户/帖子写到 volume）+ /v1 代理（SSRF 防护 + 自定义公网上游）
export CIALLO_DATA_DIR="${CIALLO_DATA_DIR:-/data}"
export CIALLO_COMMUNITY_PORT="${CIALLO_COMMUNITY_PORT:-8090}"
export CIALLO_V1_PROXY_PORT="${CIALLO_V1_PROXY_PORT:-8091}"
export CIALLO_TASK_QUEUE_PORT="${CIALLO_TASK_QUEUE_PORT:-8092}"
export CIALLO_MASTER_USERNAME="${CIALLO_MASTER_USERNAME:-admin}"
export CIALLO_MASTER_PASSWORD="${CIALLO_MASTER_PASSWORD:-}"
# 透传上游白名单 / 调试开关给 v1-proxy（compose/.env 注入）
export CIALLO_UPSTREAM_ALLOWLIST="${CIALLO_UPSTREAM_ALLOWLIST:-}"
export CIALLO_DEBUG_UPSTREAM="${CIALLO_DEBUG_UPSTREAM:-1}"
# 全局同时跑任务顶棚（各用户组并发另由 queue-policy 限制）
export CIALLO_TASK_CONCURRENCY="${CIALLO_TASK_CONCURRENCY:-8}"
export CIALLO_TASK_COMMUNITY_URL="http://127.0.0.1:${CIALLO_COMMUNITY_PORT}"
if [ -n "$CIALLO_UPSTREAM_ALLOWLIST" ]; then
  echo "[ciallo] upstream allowlist: ${CIALLO_UPSTREAM_ALLOWLIST}"
else
  echo "[ciallo] upstream allowlist: (empty — public http(s) only)"
fi
mkdir -p "$CIALLO_DATA_DIR"
node /opt/ciallo/community-api.mjs &
COMMUNITY_PID=$!
echo "[ciallo] community-api pid=${COMMUNITY_PID}"

node /opt/ciallo/v1-proxy.mjs &
V1_PROXY_PID=$!
echo "[ciallo] v1-proxy pid=${V1_PROXY_PID} port=${CIALLO_V1_PROXY_PORT}"

node /opt/ciallo/task-queue.mjs &
TASK_QUEUE_PID=$!
echo "[ciallo] task-queue pid=${TASK_QUEUE_PID} port=${CIALLO_TASK_QUEUE_PORT}"

# 等内部服务就绪再开 nginx
i=0
while [ "$i" -lt 30 ]; do
  if curl -fsS "http://127.0.0.1:${CIALLO_COMMUNITY_PORT}/healthz" >/dev/null 2>&1 \
    && curl -fsS "http://127.0.0.1:${CIALLO_V1_PROXY_PORT}/healthz" >/dev/null 2>&1 \
    && curl -fsS "http://127.0.0.1:${CIALLO_TASK_QUEUE_PORT}/healthz" >/dev/null 2>&1; then
    echo "[ciallo] community-api + v1-proxy + task-queue ready"
    break
  fi
  i=$((i + 1))
  sleep 0.2
done

cleanup() {
  echo "[ciallo] shutting down…"
  kill "$COMMUNITY_PID" 2>/dev/null || true
  kill "$V1_PROXY_PID" 2>/dev/null || true
  kill "$TASK_QUEUE_PID" 2>/dev/null || true
  wait "$COMMUNITY_PID" 2>/dev/null || true
  wait "$V1_PROXY_PID" 2>/dev/null || true
  wait "$TASK_QUEUE_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

nginx -t
exec nginx -g 'daemon off;'
