#!/bin/sh
set -eu

# 镜像只托管静态前端 + 管理门禁；上游 Base URL / API Key 全部在浏览器管理页配置。
echo "[ciallo] static SPA mode — no CIALLO_UPSTREAM (configure API in Web Admin)"

# nginx 模板无上游变量；直接拷贝即可
if [ -f /etc/nginx/nginx.conf.template ]; then
  cp /etc/nginx/nginx.conf.template /etc/nginx/nginx.conf
fi

# 运行时配置：管理页密码只注入 sha256
ADMIN_PASSWORD="$(printf '%s' "${CIALLO_ADMIN_PASSWORD:-}" | tr -d '\r')"
ADMIN_HASH=""
ADMIN_GATE="false"
if [ -n "$ADMIN_PASSWORD" ]; then
  if command -v sha256sum >/dev/null 2>&1; then
    ADMIN_HASH="$(printf '%s' "$ADMIN_PASSWORD" | sha256sum | awk '{print $1}')"
  elif command -v openssl >/dev/null 2>&1; then
    ADMIN_HASH="$(printf '%s' "$ADMIN_PASSWORD" | openssl dgst -sha256 | awk '{print $NF}')"
  else
    echo "[ciallo] warn: no sha256 tool; admin gate disabled" >&2
    ADMIN_HASH=""
  fi
  if [ -n "$ADMIN_HASH" ]; then
    ADMIN_GATE="true"
    echo "[ciallo] admin gate: enabled (password from env, hash only in runtime-config)"
  fi
else
  echo "[ciallo] admin gate: disabled (CIALLO_ADMIN_PASSWORD empty)"
fi

RUNTIME_JS="/usr/share/nginx/html/runtime-config.js"
cat > "$RUNTIME_JS" <<EOF
/* generated by entrypoint — do not edit */
window.__CIALLO_RUNTIME__ = {
  adminGateEnabled: ${ADMIN_GATE},
  adminPasswordSha256: "${ADMIN_HASH}"
};
EOF

nginx -t
exec nginx -g 'daemon off;'
