#!/bin/sh
set -eu

# CIALLO_UPSTREAM 例：
#   https://your-grok2api.example.com
#   https://your-grok2api.example.com/v1
#   http://host.docker.internal:8000
UPSTREAM="${CIALLO_UPSTREAM:-https://your-grok2api.example.com}"
UPSTREAM="$(printf '%s' "$UPSTREAM" | tr -d '\r' | sed 's/[[:space:]]//g')"

# 去掉末尾斜杠
while [ "${UPSTREAM%/}" != "$UPSTREAM" ]; do
  UPSTREAM="${UPSTREAM%/}"
done

# 去掉末尾 /v1（可重复）
case "$UPSTREAM" in
  */v1) UPSTREAM="${UPSTREAM%/v1}" ;;
esac
while [ "${UPSTREAM%/}" != "$UPSTREAM" ]; do
  UPSTREAM="${UPSTREAM%/}"
done

case "$UPSTREAM" in
  https://*|http://*)
    ;;
  *)
    echo "CIALLO_UPSTREAM must start with http:// or https://, got: ${CIALLO_UPSTREAM:-}" >&2
    exit 1
    ;;
esac

export CIALLO_UPSTREAM_ORIGIN="$UPSTREAM"

echo "[ciallo] upstream origin: $CIALLO_UPSTREAM_ORIGIN"

# 只替换我们声明的变量，避免误伤 nginx 的 $uri 等
envsubst '${CIALLO_UPSTREAM_ORIGIN}' \
  < /etc/nginx/nginx.conf.template \
  > /etc/nginx/nginx.conf

# 运行时配置：管理页密码只注入 sha256，不把明文写进静态资源
# CIALLO_ADMIN_PASSWORD 来自 compose/.env；留空则关闭门禁
ADMIN_PASSWORD="$(printf '%s' "${CIALLO_ADMIN_PASSWORD:-}" | tr -d '\r')"
ADMIN_HASH=""
ADMIN_GATE="false"
if [ -n "$ADMIN_PASSWORD" ]; then
  if command -v sha256sum >/dev/null 2>&1; then
    ADMIN_HASH="$(printf '%s' "$ADMIN_PASSWORD" | sha256sum | awk '{print $1}')"
  elif command -v openssl >/dev/null 2>&1; then
    ADMIN_HASH="$(printf '%s' "$ADMIN_PASSWORD" | openssl dgst -sha256 | awk '{print $NF}')"
  else
    echo "[ciallo] warn: no sha256 tool; admin gate disabled" >&2
    ADMIN_HASH=""
  fi
  if [ -n "$ADMIN_HASH" ]; then
    ADMIN_GATE="true"
    echo "[ciallo] admin gate: enabled (password from env, hash only in runtime-config)"
  fi
else
  echo "[ciallo] admin gate: disabled (CIALLO_ADMIN_PASSWORD empty)"
fi

RUNTIME_JS="/usr/share/nginx/html/runtime-config.js"
cat > "$RUNTIME_JS" <<EOF
/* generated by entrypoint — do not edit */
window.__CIALLO_RUNTIME__ = {
  adminGateEnabled: ${ADMIN_GATE},
  adminPasswordSha256: "${ADMIN_HASH}"
};
EOF

# 启动前做一次语法检查，失败直接退出
nginx -t

exec nginx -g 'daemon off;'
